### ISSUE TITLE
为啥我调试脚本的时候，结果正常返回了，jmeter还是提示是错的？

### ISSUE THREAD

**Issue by liuxiongkaka** [arjick/jmeter-grpc-plugin#3]
019-11-18 06:24:17,209 INFO o.a.j.r.Summariser: summary =      1 in 00:00:02 =    0.7/s Avg:   950 Min:   950 Max:   950 Err:     1 (100.00%)

**Comment by fan0412** [comment]
![image](https://user-images.githubusercontent.com/41898733/70504217-34828200-1b60-11ea-8846-bd08e02c49cc.png)

在package org.jmeter.grpc.client包中，添加这2行即可

**Comment by PillarXu** [comment]
2020-02-16 14:35:58,339 INFO o.j.g.c.GrpcClientSampler: getCallOptions CallOptions{deadline=null, authority=null, callCredentials=null, executor=null, compressorName=null, customOptions=[], waitForReady=false, maxInboundMessageSize=null, maxOutboundMessageSize=null, streamTracerFactories=[]}
2020-02-16 14:35:59,547 ERROR o.j.g.c.GrpcClientSampler: grpcCallMethod Exception
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at org.jmeter.grpc.client.GrpcClientSampler.grpcCallMethod(GrpcClientSampler.java:104) [grpc-client-sampler.jar:?]
	at org.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:81) [grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212) ~[grpc-stub-1.5.0.jar:1.5.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193) ~[grpc-stub-1.5.0.jar:1.5.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126) ~[grpc-stub-1.5.0.jar:1.5.0]
	at grpcdynamicerecog.RecogServiceGrpc$RecogServiceBlockingStub.groupAdd(RecogServiceGrpc.java:573) ~[grpc-client-sampler.jar:?]
	... 11 more
2020-02-16 14:35:59,548 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcClientSampler'.
java.lang.NullPointerException: null
	at org.apache.jmeter.samplers.SampleResult.setResponseData(SampleResult.java:744) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.jmeter.grpc.client.GrpcClientSampler.grpcCallMethod(GrpcClientSampler.java:119) ~[grpc-client-sampler.jar:?]
	at org.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:81) ~[grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
2020-02-16 14:35:59,548 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-02-16 14:35:59,548 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-02-16 14:35:59,549 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-02-16 14:35:59,549 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by PillarXu** [comment]
java.lang.reflect.InvocationTargetException: null
Caused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
这个怎么解决，是在	Object resp = apiMethod.invoke(this.blockingStub, req); 报出来的

**Comment by mymorning** [comment]
aused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
我也是相同的问题

**Comment by SherYao** [comment]
哎，我遇到相同的问题了，毫无办法，请问解决了吗

**Comment by MRliuhanran** [comment]
> 

解决了吗？咋解决？
