### ISSUE TITLE
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR Received Rst Stream

### ISSUE THREAD

**Issue by mymorning** [arjick/jmeter-grpc-plugin#6]
grpcCallMethod Exception
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.jmeter.grpc.client.GrpcClientSampler.grpcCallMethod(GrpcClientSampler.java:104) [grpc-client-sampler.jar:?]
	at org.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:81) [grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212) ~[grpc-stub-1.5.0.jar:1.5.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193) ~[grpc-stub-1.5.0.jar:1.5.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126) ~[grpc-stub-1.5.0.jar:1.5.0]
	at spiderdemo.DemoServiceGrpc$DemoServiceBlockingStub.addTest(DemoServiceGrpc.java:159) ~[grpc-client-sampler.jar:?]

这个是什么问题导致的？

**Comment by MRliuhanran** [comment]
项目带的Jmeter里\lib中有1个老包 要删掉才能读到lib\ext自己打的包
